/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/v1/logger/methods/loggingSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace v1 {
namespace logger {
namespace methods {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createloggingSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< loggingSomeIPProxy>(_address, _connection);
}

void initializeloggingSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:v1.logger.methods.logging:v1_0:logger.methods.justSendHi",
        0x123a, 0x5678, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "v1.logger.methods.logging:v1_0",
        &createloggingSomeIPProxy);
}

INITIALIZER(registerloggingSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeloggingSomeIPProxy);
}

loggingSomeIPProxy::loggingSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection)
{
}

loggingSomeIPProxy::~loggingSomeIPProxy() {
}



void loggingSomeIPProxy::requestData(CommonAPI::CallStatus &_internalCallStatus, TelemetryTypes::TelemetrySnapshot &_data, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< TelemetryTypes::TelemetrySnapshot, ::v1::v1::logger::methods::TelemetryTypes_::TelemetrySnapshotDeployment_t> deploy_data(static_cast< ::v1::v1::logger::methods::TelemetryTypes_::TelemetrySnapshotDeployment_t* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                TelemetryTypes::TelemetrySnapshot,
                ::v1::v1::logger::methods::TelemetryTypes_::TelemetrySnapshotDeployment_t
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x1),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        _internalCallStatus,
        deploy_data);
    _data = deploy_data.getValue();
}

std::future<CommonAPI::CallStatus> loggingSomeIPProxy::requestDataAsync(RequestDataAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< TelemetryTypes::TelemetrySnapshot, ::v1::v1::logger::methods::TelemetryTypes_::TelemetrySnapshotDeployment_t> deploy_data(static_cast< ::v1::v1::logger::methods::TelemetryTypes_::TelemetrySnapshotDeployment_t* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                TelemetryTypes::TelemetrySnapshot,
                ::v1::v1::logger::methods::TelemetryTypes_::TelemetrySnapshotDeployment_t
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x1),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< TelemetryTypes::TelemetrySnapshot, ::v1::v1::logger::methods::TelemetryTypes_::TelemetrySnapshotDeployment_t > _data) {
            if (_callback)
                _callback(_internalCallStatus, _data.getValue());
        },
        std::make_tuple(deploy_data));
}

void loggingSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 1;
    ownVersionMinor = 0;
}

std::future<void> loggingSomeIPProxy::getCompletionFuture() {
    return CommonAPI::SomeIP::Proxy::getCompletionFuture();
}

} // namespace methods
} // namespace logger
} // namespace v1
} // namespace v1
