/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_V1_LOGGER_METHODS_Telemetry_Types_HPP_
#define V1_V1_LOGGER_METHODS_Telemetry_Types_HPP_



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <CommonAPI/Types.hpp>
#include <cstdint>
#include <string>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace v1 {
namespace logger {
namespace methods {

struct TelemetryTypes {
    struct TelemetrySnapshot : CommonAPI::Struct< std::string, uint16_t, uint32_t> {
    
        TelemetrySnapshot()
        {
            std::get< 0>(values_) = "";
            std::get< 1>(values_) = 0u;
            std::get< 2>(values_) = 0ul;
        }
        TelemetrySnapshot(const std::string &_coreLoads, const uint16_t &_temperatureC, const uint32_t &_ramUsagePercentage)
        {
            std::get< 0>(values_) = _coreLoads;
            std::get< 1>(values_) = _temperatureC;
            std::get< 2>(values_) = _ramUsagePercentage;
        }
        inline const std::string &getCoreLoads() const { return std::get< 0>(values_); }
        inline void setCoreLoads(const std::string &_value) { std::get< 0>(values_) = _value; }
        inline const uint16_t &getTemperatureC() const { return std::get< 1>(values_); }
        inline void setTemperatureC(const uint16_t &_value) { std::get< 1>(values_) = _value; }
        inline const uint32_t &getRamUsagePercentage() const { return std::get< 2>(values_); }
        inline void setRamUsagePercentage(const uint32_t &_value) { std::get< 2>(values_) = _value; }
        inline bool operator==(const TelemetrySnapshot& _other) const {
        return (getCoreLoads() == _other.getCoreLoads() && getTemperatureC() == _other.getTemperatureC() && getRamUsagePercentage() == _other.getRamUsagePercentage());
        }
        inline bool operator!=(const TelemetrySnapshot &_other) const {
            return !((*this) == _other);
        }
    
    };


static inline const char* getTypeCollectionName() {
    static const char* typeCollectionName = "v1.logger.methods.TelemetryTypes";
    return typeCollectionName;
}

inline CommonAPI::Version getTypeCollectionVersion() {
    return CommonAPI::Version(1, 0);
}

}; // struct TelemetryTypes

} // namespace methods
} // namespace logger
} // namespace v1
} // namespace v1

namespace CommonAPI {
}


namespace std {
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_V1_LOGGER_METHODS_Telemetry_Types_HPP_
